theme: jekyll-theme-minimal
name: Make Things Happens
title: Blog
baseurl: "/blog/"
url: "https://kiril-chilingarashvili.github.io" # the base hostname & protocol for your site
timezone: PST

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
sass:
   style: expanded
   sourcemap: always